package tags

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// AddTagOKCode is the HTTP code returned for type AddTagOK
const AddTagOKCode int = 200

/*AddTagOK Success

swagger:response addTagOK
*/
type AddTagOK struct {
}

// NewAddTagOK creates AddTagOK with default headers values
func NewAddTagOK() *AddTagOK {
	return &AddTagOK{}
}

// WriteResponse to the client
func (o *AddTagOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
}
